config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions do
    resources :comments, only: %i[create destroy]

    resources :answers, except: %i[new show]
  end

  resources :answers, except: %i[new show] do
    resources :comments, only: %i[create destroy]
end

  root 'pages#index'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user

  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers
  before_action :set_question!, only: %i[show destroy edit update]
  before_action :fetch_tags, only: %i[new edit]

  def show
    load_questions_answers
    # @answers = @question.answers.order(created_at: :desc).page(params[:page])
    # @answers = Answer.where(question: @question).limit(2).order created_at: :desc
  end

  def destroy
    @question.destroy
    flash[:success] = 'Question destroy'
    redirect_to questions_path
  end

  # что нужно сделать, чтобы была возможность добавлять много вариантов ответов на один вопрос
  # каждому пользователю выбирать ответ и отображать его

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = 'Question updated!'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
    @questions = @questions.decorate
    @questions = @questions.includes(:user)
    # @questions = Question.order(created_at: :desc).page params[:page] #page разбивает коллекцию по страницам
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      flash[:success] = 'Question create'
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  # переменная образца класса
  def set_question!
    @question = Question.find params[:id]
  end

  def fetch_tags
    @tags = Tag.all
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= form_with model: @question do |f| %>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>


  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :tags %>
    </div>

    <div class="col-sm-10">
      <%= f.collection_select :tag_ids, tags, :id, :title, {}, multiple: true %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card my-3">
  <section class="card-header">
    <%= question.user.name_or_email %>
  </section>

  <div class="card-body">
    <h4><%= question.title %></h4>

    <section class="card-text">
      <time datetime="<%= question.formatted_created_at %>">
        <small><%= question.formatted_created_at %></small>
      </time>

      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150, omission: '... (continued)' %>
      </p>
    </section>

    <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
    <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
                data: {method: :delete, confirm: 'Are you sure?'} %>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>
<h1 class="mb-4">Edit Question</h1>

<%= render 'form', tags: @tags %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%== pagination @pagy %>

<%= render @questions %>

<%== pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">New question</h1>

<%= render 'form', tags: @tags %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <!-- sanitize хелпер known-safe tags and attributes  --->
  <%= sanitize @question.body %>
</div>

  <div class="mb-3">
    <%= @question.user.name_or_email %>
  </div>

<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
            data: {method: :delete, confirm: 'Are you sure?'} %>

<hr class="my-3">

<h2 class="mb-3">Write your answer</h2>

<%= render 'answers/form' %>

<h2 class="mt-5 mb-3">Answers</h2>

<%== pagination @pagy %>

<%= render partial: 'answers/answer', collection: @answers,
  as: :answer, locals: {question: @question} %>

<%== pagination @pagy %>