config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions do
    resources :comments, only: %i[create destroy]

    resources :answers, except: %i[new show]
  end

  resources :answers, except: %i[new show] do
    resources :comments, only: %i[create destroy]
end

  root 'pages#index'
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path,
                          class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path,
                          class: 'nav-link px-2', current_page: current_page %></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= nav_tab current_user.name_or_email, '#',
                          class: 'nav-link px-2 dropdown-toggle',
                          data: {"bs-toggle": 'dropdown'}, current_page: current_page %>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Edit profile', edit_user_path(current_user),
                              class: 'dropdown-item' %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to 'Log Out', session_path,
                              class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
                            class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab 'Log In', new_session_path,
                            class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>