config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions do
    resources :comments, only: %i[create destroy]

    resources :answers, except: %i[new show]
  end

  resources :answers, except: %i[new show] do
    resources :comments, only: %i[create destroy]
end

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include QuestionsAnswers
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create

  def create
    @answer = @question.answers.build answer_create_params
    if @answer.save
      flash[:success] = 'Answer created'
      redirect_to question_path(@question)
    else
      load_questions_answers(do_render: true)
    end
  end

  def update
    if @answer.update answer_update_params
      flash[:success] = 'Answer updated!'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer destroy'
    redirect_to question_path(@question)
  end

  private

  def answer_create_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <%= answer.user.name_or_email %>
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <p class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </p>
    </section>

    <%= link_to 'Edit', edit_question_answer_path(question, answer),
                class: 'btn btn-info btn-sm' %>
    <%= link_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
                data: {method: :delete, confirm: "Are you sure?"} %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control', required: true %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answer' %>
<h1>Edit Answer</h1>

<%= render 'form' %>